### ISSUE TITLE
maps on sd card not discovered

### ISSUE THREAD

**Issue by Theodin** [fransschreuder/libosmscout#4] opened 2015-06-19 19:41 UTC
I put some pregenerated map files on my sd card  (sdcard/Maps/Stuttgart/*.ind) but the app didnt pick them up. I ended up downloading them from within the app.
After seeing the different location, I copied my files to the apps settings folder inside the home folder, but the app didnt use it either.
I am using an Aquaris r23.

**Comment by fransschreuder** [comment] 2015-06-19 20:04
Hello Simeon,

If you'd read the whole thread, you wouldn't have posted this issue.
The problem is that the current version of Ubuntu doesn't allow read access to the SD card, unless you specify a rule in the apparmor file. This rule is not allowed by the Ubuntu store, unless it's a special Ubuntu Application. Appearantly OSMScout is not special enough.
Hopefully this will be fixed in a coming release of Ubuntu.

For now I published a version of OSMScout without the special rules, so it only allows read / write access to maps located in $HOME/.local/share/osmscout.fransschreuder/Maps

You should put your custom maps there for now, until this limitation of Ubuntu is fixed.

Frans

**Closed as completed** 2015-06-19 20:04 UTC

**Comment by Theodin** [comment] 2015-06-19 20:22
It doesnt work if I put them here  $HOME/.local/share/osmscout.fransschreuder/Maps/townname/*.dat either.

**Comment by fransschreuder** [comment] 2015-06-19 21:21
```
These are the files you need, (I've almost uploaded the whole world
to be downloaded from within the app though):
            "areaarea.idx",
            "bounding.dat",
            "routebicycle.dat",
            "routefoot.idx",
            "waysopt.dat",
            "areanode.idx",
            "intersections.dat",
            "routebicycle.idx",
            "standard.oss",
            "areas.dat",
            "intersections.idx",
            "routecar.dat",
            "types.dat",
            "areasopt.dat",
            "location.idx",
            "routecar.idx",
            "water.idx",
            "areaway.idx",
            "nodes.dat",
            "routefoot.dat",
            "ways.dat"

On 06/19/2015 10:22 PM, Theodin wrote:


  It doesnt work if I put them here
    $HOME/.local/share/osmscout.fransschreuder/Maps/townname/*.dat
    either.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Theodin** [comment] 2015-06-20 14:44
I saw you have almost all countries there, but I only need my bundesland and not the whole of germany, so I downloaded the area around Stuttgart (http://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez.html) as osm and built my own files using your launchpad ppa builder app. The result were all the files you mentioned except standard.oss, but it didnt work.
I will try to get a log for you later and hope it helps.
Being involved in OSM for some time I know that hosting/updating files for the whole world can become quite a challenge hosting/bandwidth-wise if the app needing it gains wider use, but I guess you have that base covered seeing as you're running an IT company :)

**Comment by fransschreuder** [comment] 2015-06-20 14:50
```
if you use the script "osmscout-import" (should be installed from
the ppa) it also copies standard.oss in the target directory.

On 06/20/2015 04:44 PM, Theodin wrote:


  I saw you have almost all countries there, but I only need my
    bundesland and not the whole of germany, so I downloaded the
    area around Stuttgart (http://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez.html)
    as osm and built my own files using your launchpad ppa builder
    app. The result were all the files you mentioned except
    standard.oss, but it didnt work.
    I will try to get a log for you later and hope it helps.
    Being involved in OSM for some time I know that hosting/updating
    files for the whole world can become quite a challenge
    hosting/bandwidth-wise if the app needing it gains wider use,
    but I guess you have that base covered seeing as you're running
    an IT company :)
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Theodin** [comment] 2015-06-20 18:39
My error log when having a map of stuttgart in my local folder and searching for said town is here: http://paste.ubuntu.com/11746829/

I used the script you mentioned and there was no standard.oss in the target folder.

**Comment by Theodin** [comment] 2015-06-20 21:34
Everything is ok now!
Trying 0.3.8, I discovered my Stuttgart map in the maps dialogue and realised that the checkbox next to the country has a meaning. Clicking on Stuttgart resulted in the main map being centered there and I now have a usable map. Thanks!

**Comment by fransschreuder** [comment] 2015-06-20 21:36
There will be a version in the open app store, allowing you to store maps on the SD card.
